---
- hosts: Ram
  become: true
  tasks: 
    - name: install python pip
      yum: 
       name: python-pipe 
       state: present
    - name: install docker-py python module
      pip: name: docker-py state: present
    - name: start container
      docker_container:
               name: container1
               image: "ganeshpandule/demoimage:{{ganraj}}"
               state: started
               published_ports: 
                    - 0.0.0.0:8080:8080
     
